export const translate = {
    KA: {
        'drawer.home':'მთავარი',
        'landing.marketplace': 'მაღაზია',
        'landing.about': 'ჩვენს შესახებ',
        'landing.materials' : 'მასალები',
        'landing.login':"შესვლა",
        'landing.button':  'დაწყება',
        'landing.title': '3D ბეჭდვის სერვისი',
        'landing.desc': 'აქციე წარმოსახვა რეალოდბად. იდეალური დამხმარე შენი სტარტაპისთვის',
        'landing.trending':'პოპულარული პროდუქტები',
        'landing.blog': 'ბლოგი',
        'marketplace.categories':'კატეგორიები',
        'categories.household':'სახლი',
        'categories.plants':'მცენარეები',
        'categories.decorations':'დეკორაციები',
        'categories.kitchen':'სამზარეულო',
        'categories.keychains':'საკიდები',
        'categories.accessories':'აქსესუარები',
        'categories.goodtohaves':'საინტერესო',
        'categories.cars':'მანქანა',
        'categories.office':'ოფისი',
        'categories.organizers':'ორგანიზატორები',
        'categories.decoration':'დეკორაციები',
        'categories.fidgets':'გასართობები',
        'categories.christmas':'საშობაო',
        'footer.cta.title': 'მზად ხართ დასაწყებად?',
        'footer.cta.description': 'პროდუქტის განვითარებიდან ინდუსტრიულ 3D წარმოებამდე, ჩვენ შეგვიძლია დაგეხმაროთ თქვენი ბიზნესის გაფართოებაში.',
        'footer.cta.contact': 'კონტაქტი',
        'footer.services.title': 'სერვისები',
        'footer.services.3dDesign': '3D დიზაინი',
        'footer.services.3dPrinting': '3D ბეჭდვა',
        'footer.services.additiveManufacturing': 'დანამატი წარმოება',
        'footer.services.business': 'ბიზნესი',
        'footer.support.title': 'მხარდაჭერა',
        'footer.support.contact': 'დაგვიკავშირდით',
        'footer.support.help': 'დახმარების ცენტრი',
        'footer.support.materials': '3D მასალების გზამკვლევი',
        'footer.support.students': 'სტუდენტებისთვის',
        'footer.company.title': 'Makers Hub',
        'footer.company.about': 'ჩვენს შესახებ',
        'footer.company.blog': 'ბლოგი',
        'footer.company.press': 'პრესა',
        'footer.company.careers': 'კარიერა',
        'footer.company.invite': 'მოიწვიე მეგობარი',
        'footer.company.giftCards': 'საჩუქრის ბარათები',
        'footer.company.newsletter': 'სიახლეების გამოწერა',
        'footer.copyright': '© {year} Makers Hub. ყველა უფლება დაცულია.',
        'navbar.admin.orders': ' შეკვეთები',
        'navbar.admin.listings': 'ადმინ სიები',
        'navbar.greeting': 'გამარჯობა',
        'about.hero.title': 'Makers Hub - 3D ბეჭდვის ჰაბი საქართველოში',
        'about.hero.subtitle': 'ჩვენ ვქმნით მომავალს, სადაც წარმოსახვა ხდება რეალობა',
        'about.story.title': 'ჩვენი ისტორია',
        'about.story.paragraph1': '5 წლის გამოცდილება 3D ბეჭდვის სფეროში გვაძლევს საშუალებას, რომ შევქმნათ რაღაც განსაკუთრებული. Makers Hub შეიქმნა, რათა დავაკავშიროთ მეიკერები მთელ საქართველოში და გავხადოთ წარმოება უფრო მარტივი და ხელმისაწვდომი.',
        'about.story.paragraph2': 'ჩვენი მიზანია შევთავაზოთ ჩვენს ხალხს ადგილობრივი, ხარისხიანი პროდუქტები, რომლებიც გაუმჯობესებს ყოველდღიურ ცხოვრებას და მხარს დაუჭერს ადგილობრივ მწარმოებლებს.',
        'about.mission.title': 'ჩვენი მისია',
        'about.mission.collaboration.title': 'თანამშრომლობა',
        'about.mission.collaboration.text': 'ვმუშაობთ მეიკერებთან საქართველოს მასშტაბით, რათა შევქმნათ ძლიერი და კრეატიული საზოგადოება.',
        'about.mission.local.title': 'ადგილობრივი წარმოება',
        'about.mission.local.text': 'ვთავაზობთ ხარისხიან, ადგილობრივად დამზადებულ პროდუქტებს, რომლებიც მხარს უჭერს ჩვენს ეკონომიკას.',
        'about.mission.easy.title': 'მარტივი წარმოება',
        'about.mission.easy.text': 'ვხდით წარმოებას უფრო მარტივს და ხელმისაწვდომს ყველასთვის - დიზაინერებიდან დაწყებული მცირე ბიზნესებამდე.',
        'about.values.title': 'ჩვენი ღირებულებები',
        'about.values.eco.title': 'ეკოლოგიური მასალები',
        'about.values.eco.text': 'ვიყენებთ ბიოდაშლად მასალებს და მხარს ვუჭერთ მდგრად წარმოებას, რათა დავცვათ ჩვენი პლანეტა მომავალ თაობებთვის.',
        'about.values.innovation.title': 'ინოვაცია',
        'about.values.innovation.text': 'მუდმივად ვცდილობთ გავაუმჯობესოთ ჩვენი ტექნოლოგიები და პროცესები, რათა შევთავაზოთ საუკეთესო გადაწყვეტილებები.',
        'about.values.quality.title': 'ხარისხი',
        'about.values.quality.text': 'ყოველი პროდუქტი იწარმოება უმაღლესი სტანდარტებით, რათა დავრწმუნდეთ, რომ ჩვენი კლიენტები იღებენ საუკეთესოს.',
        'about.values.community.title': 'საზოგადოება',
        'about.values.community.text': 'ვქმნით საზოგადოებას, სადაც მეიკერები შეუძლიათ გაზიარონ იდეები, შეისწავლონ და ერთად შექმნან რაღაც განსაკუთრებული.',
        'about.impact.title': 'როგორ ვაუმჯობესებთ ცხოვრებას',
        'about.impact.daily.title': 'ყოველდღიური ცხოვრების გაუმჯობესება',
        'about.impact.daily.text': 'ჩვენი პროდუქტები - სახლის ორგანიზატორებიდან დაწყებული დეკორაციებამდე - ეხმარება ხალხს ორგანიზებულად და ეფექტურად იცხოვრონ. ყოველი პროდუქტი შექმნილია, რათა გადაჭრას რეალური პრობლემები და გააუმჯობესოს ყოველდღიური ცხოვრება.',
        'about.impact.customization.title': 'ინდივიდუალური მიდგომა',
        'about.impact.customization.text': '3D ბეჭდვა საშუალებას გვაძლევს შევქმნათ სრულად პერსონალიზებული პროდუქტები, რომლებიც შეესაბამება თითოეული ადამიანის უნიკალურ საჭიროებებსა და პრეფერენციებს.',
        'about.impact.accessibility.title': 'ხელმისაწვდომობა',
        'about.impact.accessibility.text': 'ვხდით 3D ბეჭდვას ხელმისაწვდომს ყველასთვის - მცირე ბიზნესებიდან დაწყებული ინდივიდუალურ მომხმარებლებამდე. ჩვენი პლატფორმა გაამარტივებს პროცესს საწყისიდან დასრულებამდე.',
        'about.impact.sustainability.title': 'მდგრადობა',
        'about.impact.sustainability.text': 'ბიოდაშლად მასალების გამოყენებით და ადგილობრივი წარმოების მხარდაჭერით, ჩვენ ვქმნით უფრო მდგრად და ეკოლოგიურად სუფთა მომავალს.',
        'about.cta.title': 'მოდი ერთად შევქმნათ რაღაც განსაკუთრებული',
        'about.cta.text': 'თუ თქვენ ხართ მეიკერი, დიზაინერი ან უბრალოდ გაქვთ იდეა, რომელიც გსურთ რეალობად აქციოთ - ჩვენ აქ ვართ, რათა დაგეხმაროთ.',
        'newYear.title': '🎄 ახალი წლის კოლექცია',
        'newYear.subtitle': 'აღმოაჩინეთ ჩვენი საშობაო პროდუქტები',
        'newYear.empty': 'ამჟამად პროდუქტები არ არის ხელმისაწვდომი.',
        'newYear.seeAll': 'ყველას ნახვა',
        'product.price': 'ფასი',
        'drawer.welcome': 'კეთილი იყოს თქვენი დაბრუნება',
        'drawer.signIn': 'შესვლა',
        'drawer.createAccount': 'ანგარიშის შექმნა',
        'materials.hero.title': 'FDM პრინტერის მასალები',
        'materials.hero.subtitle': 'აღმოაჩინეთ სრული სპექტრი მაღალი ხარისხის 3D ბეჭდვის მასალებისა',
        'materials.intro.title': 'FDM ბეჭდვის მასალები',
        'materials.intro.text': 'Fused Deposition Modeling (FDM) არის ყველაზე პოპულარული 3D ბეჭდვის ტექნოლოგია. ჩვენ გთავაზობთ მრავალფეროვან მასალებს, რომლებიც შეესაბამება სხვადასხვა გამოყენების სფეროს - დაწყებული მარტივი პროტოტიპებისგან დამთავრებული მაღალი მოთხოვნის ინდუსტრიული კომპონენტებით.',
        'materials.specs.temp': 'ნოზლის ტემპერატურა',
        'materials.specs.bed': 'ბედის ტემპერატურა',
        'materials.specs.difficulty': 'სირთულე',
        'materials.specs.easy': 'ადვილი',
        'materials.specs.medium': 'საშუალო',
        'materials.specs.hard': 'რთული',
        'materials.specs.advanced': 'მოწინავე',
        'materials.comparison.title': 'მასალების შედარება',
        'materials.comparison.material': 'მასალა',
        'materials.comparison.strength': 'სიძლიერე',
        'materials.comparison.flexibility': 'მოქნილობა',
        'materials.comparison.temp': 'ტემპერატურული წინააღმდეგობა',
        'materials.comparison.best': 'საუკეთესო გამოყენება',
        'materials.comparison.pla': 'დეკორაციები, პროტოტიპები',
        'materials.comparison.abs': 'ფუნქციური ნაწილები, მექანიკური კომპონენტები',
        'materials.comparison.petg': 'გამჭვირვალე ნაწილები, ქიმიური წინააღმდეგობა',
        'materials.comparison.tpu': 'მოქნილი ნაწილები, სათამაშოები',
        'materials.comparison.nylon': 'ინდუსტრიული კომპონენტები, მაღალი დატვირთვა',
        'materials.tips.title': 'სასარგებლო რჩევები',
        'materials.tips.temp.title': 'ტემპერატურის კონტროლი',
        'materials.tips.temp.text': 'თითოეულ მასალას აქვს თავისი ოპტიმალური ბეჭდვის ტემპერატურა. სწორი ტემპერატურა უზრუნველყოფს საუკეთესო შედეგებს და თავიდან აცილებს ბეჭდვის პრობლემებს.',
        'materials.tips.moisture.title': 'ტენიანობის კონტროლი',
        'materials.tips.moisture.text': 'ფილამენტები უნდა ინახებოდეს მშრალ და ვენტილირებად ადგილას. ტენიანი ფილამენტი შეიძლება გამოიწვიოს ბეჭდვის პრობლემები და ხარისხის დაქვეითება.',
        'materials.tips.layer.title': 'ფენის სისქე',
        'materials.tips.layer.text': 'ფენის სისქე გავლენას ახდენს ბეჭდვის ხარისხსა და სიჩქარეზე. 0.1-0.2mm ფენები იძლევა გლუვ ზედაპირს, ხოლო 0.3mm და მეტი ფენები უფრო სწრაფია.',
        'materials.tips.speed.title': 'ბეჭდვის სიჩქარე',
        'materials.tips.speed.text': 'სხვადასხვა მასალებს აქვთ განსხვავებული ოპტიმალური ბეჭდვის სიჩქარე. ზოგადად, 40-60mm/s სიჩქარე იძლევა საუკეთესო შედეგებს უმეტეს მასალებში.',
        'materials.overview.title': 'რა არის FDM ბეჭდვა?',
        'materials.overview.paragraph1': 'Fused Deposition Modeling (FDM) არის ყველაზე პოპულარული 3D ბეჭდვის ტექნოლოგია, რომელიც იყენებს თერმოპლასტიკურ ფილამენტებს ობიექტების შესაქმნელად. ეს მეთოდი იდეალურია როგორც პროტოტიპების, ასევე ფუნქციური ნაწილების წარმოებისთვის.',
        'materials.overview.paragraph2': 'ჩვენ გთავაზობთ მრავალფეროვან მასალებს, რომლებიც შეესაბამება სხვადასხვა გამოყენების სფეროს - დაწყებული მარტივი პროტოტიპებისგან დამთავრებული მაღალი მოთხოვნის ინდუსტრიული კომპონენტებით.',
        'materials.types.title': 'მასალების ტიპები',
        'materials.types.pla.title': 'PLA (Polylactic Acid)',
        'materials.types.pla.description': 'PLA არის ყველაზე პოპულარული მასალა დამწყებთათვის. იგი ადვილად იბეჭდება, აქვს ბუნებრივი წარმოშობა და ბიოდაშლადია. იდეალურია დეკორაციული ნივთებისა და პროტოტიპებისთვის.',
        'materials.types.abs.title': 'ABS (Acrylonitrile Butadiene Styrene)',
        'materials.types.abs.description': 'ABS არის ძლიერი და გამძლე მასალა, რომელიც გამოირჩევა მაღალი ტემპერატურის წინააღმდეგობით. შესანიშნავია ფუნქციური ნაწილებისა და მექანიკური კომპონენტებისთვის.',
        'materials.types.petg.title': 'PETG (Polyethylene Terephthalate Glycol)',
        'materials.types.petg.description': 'PETG აერთიანებს PLA-ს სიმარტივეს და ABS-ის სიძლიერეს. გამჭვირვალე, ქიმიურად წინააღმდეგობითი და შესანიშნავია ფუნქციური აპლიკაციებისთვის.',
        'materials.types.tpu.title': 'TPU (Thermoplastic Polyurethane)',
        'materials.types.tpu.description': 'TPU არის მოქნილი და ელასტიური მასალა, რომელიც შესანიშნავია ნაწილებისთვის, რომლებიც საჭიროებენ დეფორმაციას. იდეალურია სათამაშოების, ჩანთებისა და დამცავი საფარებისთვის.',
        'materials.types.nylon.title': 'Nylon',
        'materials.types.nylon.description': 'Nylon არის მაღალი სიძლიერის მასალა, რომელიც გამოირჩევა მაღალი ტემპერატურისა და ცვეთის წინააღმდეგობით. შესანიშნავია ინდუსტრიული და ინჟინერული აპლიკაციებისთვის.',
        'materials.types.specialty.title': 'სპეციალური მასალები',
        'materials.types.specialty.description': 'ჩვენ ასევე გთავაზობთ სპეციალურ მასალებს, როგორიცაა ხის, ლითონის, ნახშირბადის ბოჭკოს შემცველი და სხვა კომპოზიტური ფილამენტები უნიკალური თვისებებისთვის.',
        'materials.properties.title': 'მასალების თვისებები',
        'materials.properties.easy': 'ადვილი',
        'materials.properties.eco': 'ეკოლოგიური',
        'materials.properties.versatile': 'მრავალფეროვანი',
        'materials.properties.strong': 'ძლიერი',
        'materials.properties.durable': 'გამძლე',
        'materials.properties.heat': 'სითბოს წინააღმდეგობა',
        'materials.properties.clear': 'გამჭვირვალე',
        'materials.properties.chemical': 'ქიმიური წინააღმდეგობა',
        'materials.properties.flexible': 'მოქნილი',
        'materials.properties.wear': 'ცვეთის წინააღმდეგობა',
        'materials.properties.impact': 'ზემოქმედების წინააღმდეგობა',
        'materials.properties.lightweight': 'მსუბუქი',
        'materials.properties.industrial': 'ინდუსტრიული',
        'materials.properties.wood': 'ხის ეფექტი',
        'materials.properties.metal': 'ლითონის ეფექტი',
        'materials.properties.carbon': 'ნახშირბადის ბოჭკო',
        'materials.properties.strength.title': 'სიძლიერე და გამძლეობა',
        'materials.properties.strength.text': 'თითოეულ მასალას აქვს თავისი უნიკალური სიძლიერის და გამძლეობის მახასიათებლები. PLA შესანიშნავია დეკორაციული ნივთებისთვის, ხოლო ABS და Nylon იდეალურია ფუნქციური კომპონენტებისთვის, რომლებიც საჭიროებენ მაღალ მექანიკურ დატვირთვას.',
        'materials.properties.temperature.title': 'ტემპერატურული წინააღმდეგობა',
        'materials.properties.temperature.text': 'სხვადასხვა მასალებს აქვთ განსხვავებული ტემპერატურული მახასიათებლები. ABS და PETG შესანიშნავად იტანენ მაღალ ტემპერატურებს, რაც მათ იდეალურს ხდის ავტომობილებისა და ელექტრონიკის კომპონენტებისთვის.',
        'materials.properties.flexibility.title': 'მოქნილობა და ელასტიურობა',
        'materials.properties.flexibility.text': 'TPU და სხვა მოქნილი მასალები საშუალებას იძლევა შევქმნათ ნაწილები, რომლებიც საჭიროებენ დეფორმაციას და დაბრუნებას თავდაპირველ ფორმაში. იდეალურია სათამაშოების, ჩანთებისა და დამცავი საფარებისთვის.',
        'materials.properties.finish.title': 'ზედაპირის დასრულება',
        'materials.properties.finish.text': 'თითოეულ მასალას აქვს თავისი უნიკალური ზედაპირის ტექსტურა. PLA იძლევა გლუვ და ბრწყინვალე ზედაპირს, ხოლო PETG შესანიშნავია გამჭვირვალე ნაწილებისთვის. სპეციალური მასალები, როგორიცაა ხის ან ლითონის ფილამენტები, იძლევა უნიკალურ ვიზუალურ ეფექტებს.',
        'materials.applications.title': 'გამოყენების სფეროები',
        'materials.applications.home.title': 'საყოფაცხოვრებო ნივთები',
        'materials.applications.home.text': 'შექმენით პერსონალიზებული საყოფაცხოვრებო ნივთები - ორგანიზატორებიდან დაწყებული დეკორაციული ელემენტებით. PLA და PETG შესანიშნავია ამ მიზნებისთვის.',
        'materials.applications.prototyping.title': 'რაპიდ პროტოტიპირება',
        'materials.applications.prototyping.text': 'FDM ბეჭდვა იდეალურია სწრაფი პროტოტიპების შესაქმნელად. PLA-ს დაბალი ღირებულება და ადვილი გამოყენება მას ხდის პოპულარულ არჩევანს დიზაინერებისა და ინჟინერებისთვის.',
        'materials.applications.art.title': 'ხელოვნება და დიზაინი',
        'materials.applications.art.text': '3D ბეჭდვა გახსნა ახალ შესაძლებლობებს ხელოვნებაში. შექმენით უნიკალური სკულპტურები, დეკორაციები და ხელოვნების ნივთები სპეციალური მასალების გამოყენებით.',
        'materials.applications.functional.title': 'ფუნქციური ნაწილები',
        'materials.applications.functional.text': 'ABS, PETG და Nylon შესანიშნავია ფუნქციური ნაწილების წარმოებისთვის, რომლებიც საჭიროებენ მაღალ სიძლიერეს, გამძლეობას და ტემპერატურულ წინააღმდეგობას.',
        'materials.bestPractices.title': 'საუკეთესო პრაქტიკები',
        'materials.bestPractices.temperature.title': 'ტემპერატურის კონტროლი',
        'materials.bestPractices.temperature.text': 'თითოეულ მასალას აქვს თავისი ოპტიმალური ბეჭდვის ტემპერატურა. PLA-სთვის რეკომენდებულია 190-220°C, ABS-ისთვის 220-250°C, ხოლო PETG-სთვის 220-250°C. სწორი ტემპერატურა უზრუნველყოფს საუკეთესო შედეგებს.',
        'materials.bestPractices.layer.title': 'ფენის სისქე',
        'materials.bestPractices.layer.text': 'ფენის სისქე გავლენას ახდენს ბეჭდვის ხარისხსა და სიჩქარეზე. 0.1-0.2mm ფენები იძლევა გლუვ ზედაპირს, ხოლო 0.3mm და მეტი ფენები უფრო სწრაფია, მაგრამ ნაკლებად გლუვი.',
        'materials.bestPractices.storage.title': 'მასალების შენახვა',
        'materials.bestPractices.storage.text': 'ფილამენტები უნდა ინახებოდეს მშრალ და ვენტილირებად ადგილას, რათა თავიდან ავიცილოთ ტენიანობის შთანთქმა. ტენიანი ფილამენტი შეიძლება გამოიწვიოს ბეჭდვის პრობლემები და ხარისხის დაქვეითება.',
        'materials.bestPractices.quality.title': 'ხარისხის კონტროლი',
        'materials.bestPractices.quality.text': 'ჩვენ ვიყენებთ მხოლოდ მაღალი ხარისხის ფილამენტებს, რომლებიც გადიან მკაცრ ხარისხის კონტროლს. ეს უზრუნველყოფს თანმიმდევრულ და საიმედო ბეჭდვის შედეგებს თითოეულ პროექტში.',
        'materials.cta.title': 'მზად ხართ დაიწყოთ თქვენი პროექტი?',
        'materials.cta.text': 'კონტაქტში შემოდით ჩვენთან, რათა განვიხილოთ თქვენი მასალების საჭიროებები და ვიპოვოთ სრულყოფილი გადაწყვეტა თქვენი პროექტისთვის.',
        'contact.hero.title': 'დაგვიკავშირდით',
        'contact.hero.subtitle': 'ჩვენ ყოველთვის მზად ვართ დაგეხმაროთ თქვენს კითხვებსა და პროექტებში',
        'contact.form.title': 'გამოგვიგზავნეთ შეტყობინება',
        'contact.form.description': 'შეავსეთ ფორმა ქვემოთ და ჩვენ მალე დაგიკავშირდებით',
        'contact.form.name': 'სახელი',
        'contact.form.namePlaceholder': 'შეიყვანეთ თქვენი სახელი',
        'contact.form.email': 'ელფოსტა',
        'contact.form.emailPlaceholder': 'თქვენი.ელფოსტა@მაგალითი.com',
        'contact.form.subject': 'თემა',
        'contact.form.subjectPlaceholder': 'რაზე გსურთ დაგვიკავშირდეთ?',
        'contact.form.message': 'შეტყობინება',
        'contact.form.messagePlaceholder': 'დაწერეთ თქვენი შეტყობინება აქ...',
        'contact.form.submit': 'გაგზავნა',
        'contact.form.sending': 'იგზავნება...',
        'contact.success': 'შეტყობინება წარმატებით გაიგზავნა! ჩვენ მალე დაგიკავშირდებით.',
        'contact.error': 'დაფიქსირდა შეცდომა. გთხოვთ სცადოთ მოგვიანებით.',
        'contact.info.email.title': 'ელფოსტა',
        'contact.info.email.text': 'info@makershub.ge',
        'contact.info.location.title': 'მდებარეობა',
        'contact.info.location.text': 'საქართველო',
        'contact.info.hours.title': 'სამუშაო საათები',
        'contact.info.hours.text': 'ორშაბათი - პარასკევი: 10:00 - 18:00',
        'product.madeBy': 'დამზადებულია',
        'product.ships': 'გაგზავნა 7 დღეში',
        'product.color': 'ფერი:',
        'product.quantity': 'რაოდენობა:',
        'product.addToCart': 'კალათაში დამატება',
        'product.question': 'გაქვთ შეკითხვა ამ პროდუქტზე?',
        'product.loginRequired': 'დიზაინერთან დასაკავშირებლად უნდა იყოთ შესული და დადასტურებული.',
        'product.about': 'პროდუქტის შესახებ',
        'product.noDescription': 'ამ პროდუქტისთვის აღწერა არ არის ხელმისაწვდომი.',
        'product.information': 'პროდუქტის ინფორმაცია',
        'product.category': 'კატეგორია',
        'product.subcategory': 'ქვეკატეგორია',
        'product.createdBy': 'შექმნილია',
        'product.shipping': 'მიწოდება',
        'product.shippingTime': '7-14 სამუშაო დღე',
        'checkout.confirmOrder': 'დაადასტურეთ თქვენი შეკვეთა',
        'checkout.confirmDescription': 'გთხოვთ გადაამოწმოთ მიწოდების დეტალები და დაასრულოთ ხელით ბანკის გადარიცხვა დასასრულებლად.',
        'checkout.shippingDetails': 'მიწოდების დეტალები',
        'checkout.fullName': 'სრული სახელი*',
        'checkout.fullNamePlaceholder': 'შეიყვანეთ თქვენი სრული სახელი',
        'checkout.company': 'კომპანია',
        'checkout.companyPlaceholder': 'კომპანია (არასავალდებულო)',
        'checkout.addressLine': 'მისამართის ხაზი*',
        'checkout.addressLinePlaceholder': 'ქუჩა და ნომერი',
        'checkout.addressLine2': 'მისამართის ხაზი 2',
        'checkout.addressLine2Placeholder': 'ბინა, ოთახი და ა.შ. (არასავალდებულო)',
        'checkout.city': 'ქალაქი*',
        'checkout.cityPlaceholder': 'ქალაქი',
        'checkout.phone': 'ტელეფონი*',
        'checkout.phonePlaceholder': '+995 ...',
        'checkout.orderNotes': 'შეკვეთის შენიშვნები',
        'checkout.orderNotesPlaceholder': 'დაამატეთ სპეციალური ინსტრუქციები (არასავალდებულო)',
        'checkout.orderSummary': 'შეკვეთის შეჯამება',
        'checkout.qty': 'რაოდენობა',
        'checkout.subtotal': 'ქვეჯამი',
        'checkout.shipping': 'მიწოდება',
        'checkout.total': 'სულ',
        'checkout.cancel': 'გაუქმება',
        'checkout.placingOrder': 'შეკვეთა იგზავნება…',
        'checkout.placeOrder': 'შეკვეთის გაფორმება და ბანკის დეტალების ჩვენება',
        'checkout.orderCreated': 'შეკვეთა შექმნილია',
        'checkout.orderCreatedDescription': 'გთხოვთ, ბანკის გადარიცხვის შესრულებისას დანიშნულებაში მიუთითოთ შეკვეთის ნომერი. გადახდები ჩვეულებრივ 30 წუთში რეგისტრირდება—როგორც კი ჩვენ დავადასტურებთ თანხას, განვაახლებთ შეკვეთის სტატუსს და დავიწყებთ წარმოებას.',
        'checkout.paymentReference': 'გადახდის მითითება',
        'checkout.copy': 'კოპირება',
        'checkout.transferDetails': 'გადარიცხვის დეტალები',
        'checkout.transferInstructions': 'გადარიცხეთ თანხა მოცემულ ანგარიშზე და დანიშნულებასი მიუთითეთ შეკვეთის ნომერი. თუ უკვე გადაიხადეთ, სტატუსი ავტომატურად განახლდება, როგორც კი გადარიცხვა დასრულდება; თუ დახმარება გჭირდებათ, თავისუფლად უპასუხეთ დადასტურების ელფოსტას.',
        'checkout.payee': 'მიმღები',
        'checkout.bank': 'ბანკი',
        'checkout.bankAddress': 'ბანკის მისამართი',
        'checkout.accountNumber': 'ანგარიშის ნომერი',
        'checkout.swift': 'SWIFT',
        'checkout.amount': 'თანხა',
        'checkout.close': 'დახურვა',
        'checkout.viewOrderHistory': 'შეკვეთების ისტორიის ნახვა',
        'checkout.cartEmpty': 'თქვენი კალათა ცარიელია.',
        'checkout.fillRequired': 'გთხოვთ შეავსოთ თქვენი სრული სახელი, მისამართი და ტელეფონის ნომერი.',
        'checkout.orderError': 'შეკვეთის შექმნა შეუძლებელია. გთხოვთ სცადოთ მოგვიანებით.',
        'checkout.profileError': 'შენახული პროფილის დეტალების ჩატვირთვა შეუძლებელია.',
        'profile.loading': 'თქვენი პროფილი იტვირთება…',
        'profile.title': 'თქვენი პროფილი',
        'profile.description': 'პროფილის პარამეტრები და შეკვეთების ისტორია',
        'profile.name': 'სახელი',
        'profile.email': 'ელფოსტა',
        'profile.accountCreated': 'ანგარიში შექმნილია',
        'profile.authProvider': 'ავტორიზაციის პროვაიდერი',
        'profile.accessLevel': 'წვდომის დონე',
        'profile.administrator': 'ადმინისტრატორი',
        'profile.customer': 'მომხმარებელი',
        'profile.startProject': 'ახალი პროექტის დაწყება',
        'profile.signOut': 'გასვლა',
        'profile.loadError': 'პროფილის მონაცემების ჩატვირთვა შეუძლებელია.',
        'profile.recentActivity': 'ბოლო აქტივობა',
        'profile.noPurchases': 'თქვენ ჯერ არ გაქვთ შესყიდვები',
        'profile.noPurchasesDesc': 'როდესაც შეუკვეთებთ, თქვენი შეკვეთები გამოჩნდება აქ, რათა შეძლოთ ფაილების ხელახლა ნახვა, ინვოისების ჩამოტვირთვა ან ერთი დაწკაპუნებით ხელახლა შეკვეთა.',
        'profile.latestPurchases': 'თქვენი ბოლო შესყიდვები',
        'profile.latestPurchasesDesc': 'თვალყურს ადევნეთ შესრულების პროგრესს, ჩამოტვირთეთ მიწოდებადი ნივთები და გამოიკვლიეთ რეკომენდებული დამატებები.',
        'profile.order': 'შეკვეთა',
        'profile.placedOn': 'გაფორმებულია',
        'profile.qty': 'რაოდენობა',
        'profile.viewDetails': 'დეტალების ნახვა',
        'profile.status.awaitingPayment': 'გადახდა მოლოდინშია',
        'profile.status.paymentReceived': 'გადახდა მიღებულია',
        'profile.status.processing': 'დამუშავება',
        'profile.status.fulfilled': 'შესრულებულია',
        'profile.status.cancelled': 'გაუქმებულია',
        'profile.orderDetails.awaitingTransfer': 'ველოდებით თანხის გადარიცხვას',
        'profile.orderDetails.paymentIntro': 'ჩვენ ვინახავთ ამ შეკვეთას გადახდის მიღებამდე. გთხოვთ გადარიცხოთ სრული თანხა ქვემოთ მოცემულ ანგარიშის ნომერზე და დანიშნულებაში მიუთითოთ შეკვეთის ნომერი. ბანკის გადარიცხვები ჩვეულებრივ 30 წუთში ჩანს; თუ უკვე გადაიხადეთ, სტატუსი ავტომატურად განახლდება.',
        'profile.orderDetails.paymentReference': 'შეკვეთის ნომერი',
        'profile.orderDetails.copy': 'კოპირება',
        'profile.orderDetails.payee': 'მიმღები',
        'profile.orderDetails.bank': 'ბანკი',
        'profile.orderDetails.bankAddress': 'ბანკის მისამართი',
        'profile.orderDetails.accountNumber': 'ანგარიშის ნომერი',
        'profile.orderDetails.swift': 'SWIFT',
        'profile.orderDetails.amount': 'თანხა',
        'profile.orderDetails.paymentHelp': 'თუ 30 წუთზე მეტი გავიდა თანხის გადარიცხვიდან და სტატუსი ჯერ კიდევ არ შეცვლილა, მოგვწერეთ მეილზე. ასევე გაითვალისწინეთ რომ არასამუშაო დღეებში სტატუსის განახლებას შეიძლება მეტი დრო დასჭირდეს ',
        'profile.orderDetails.items': 'ნივთები',
        'profile.orderDetails.shipping': 'მიწოდება',
        'profile.orderDetails.recipient': 'მიმღები',
        'profile.orderDetails.company': 'კომპანია',
        'profile.orderDetails.addressLine1': 'მისამართის ხაზი 1',
        'profile.orderDetails.addressLine2': 'მისამართის ხაზი 2',
        'profile.orderDetails.city': 'ქალაქი',
        'profile.orderDetails.phone': 'ტელეფონი',
        'profile.orderDetails.billing': 'გადახდა',
        'profile.orderDetails.customerNotes': 'მომხმარებლის შენიშვნები',
        'profile.orderDetails.subtotal': 'ქვეჯამი',
        'profile.orderDetails.shipping': 'მიწოდება',
        'profile.orderDetails.total': 'სულ',
        'profile.orderDetails.close': 'დახურვა',
        'cart.recentlyAdded': 'ბოლოს დამატებული:',
        'cart.empty': 'თქვენი კალათა ცარიელია',
        'cart.emptyDesc': 'როგორც ჩანს, თქვენ ჯერ არ დაუმატებიათ ნივთები კალათაში.',
        'cart.continueShopping': '← შეძენის გაგრძელება',
        'cart.myCart': 'ჩემი კალათა',
        'cart.item': 'ნივთი',
        'cart.items': 'ნივთები',
        'cart.orderSummary': 'შეკვეთის შეჯამება',
        'cart.subtotal': 'ქვეჯამი',
        'cart.estimatedShipping': 'სავარაუდო მიწოდება',
        'cart.free': 'უფასო',
        'cart.total': 'სულ',
        'cart.proceedToCheckout': 'გადახდაზე გადასვლა',
        'cart.shippingNote': 'უფასო მიწოდება ₾50-ზე მეტ შეკვეთებზე',
    }, 
    EN: {
        'landing.marketplace': 'Marketplace',
        'landing.about': 'About',
        'landing.materials': 'Materials',
        'landing.login': 'Sign In',
        'landing.button': 'Start',
        'landing.title': '3D Printing Service',
        'landing.desc': 'Turn imagination into reality. The perfect assistant for your startup',
        'landing.trending': 'Popular Products',
        'landing.blog': 'Blog',
        'marketplace.categories': 'Categories',
        'categories.household': 'Household',
        'categories.plants': 'Plants',
        'categories.decorations': 'Decorations',
        'categories.kitchen': 'Kitchen',
        'categories.keychains': 'Keychains',
        'categories.accessories': 'Accessories',
        'categories.goodtohaves': 'Good to Have',
        'categories.cars': 'Cars',
        'categories.office': 'Office',
        'categories.organizers': 'Organizers',
        'categories.decoration': 'Decorations',
        'categories.fidgets': 'Fidgets',
        'categories.christmas': 'Christmas',
        'footer.cta.title': 'Ready to get started?',
        'footer.cta.description': 'From product development to industrial 3D manufacturing, we can help you scale your business.',
        'footer.cta.contact': 'Contact',
        'footer.services.title': 'Services',
        'footer.services.3dDesign': '3D Design',
        'footer.services.3dPrinting': '3D Printing',
        'footer.services.additiveManufacturing': 'Additive Manufacturing',
        'footer.services.business': 'Business',
        'footer.support.title': 'Support',
        'footer.support.contact': 'Contact Us',
        'footer.support.help': 'Help Center',
        'footer.support.materials': '3D Materials Guide',
        'footer.support.students': 'For Students',
        'footer.company.title': 'Makers Hub',
        'footer.company.about': 'About',
        'footer.company.blog': 'Blog',
        'footer.company.press': 'Press',
        'footer.company.careers': 'Careers',
        'footer.company.invite': 'Invite a Friend',
        'footer.company.giftCards': 'Gift Cards',
        'footer.company.newsletter': 'Newsletter Signup',
        'footer.copyright': '© {year} Makers Hub. All rights reserved.',
        'navbar.admin.orders': 'Admin Orders',
        'navbar.admin.listings': 'Admin Listings',
        'navbar.greeting': 'Hi',
        'about.hero.title': 'Makers Hub - 3D Printing Hub in Georgia',
        'about.hero.subtitle': 'We create the future where imagination becomes reality',
        'about.story.title': 'Our Story',
        'about.story.paragraph1': 'With 5 years of experience in 3D printing, we decided to create something special. Makers Hub was born to connect makers across Georgia and make production easier and more accessible for everyone.',
        'about.story.paragraph2': 'Our goal is to offer our people local, high-quality products that improve daily life while supporting local manufacturers and creators.',
        'about.mission.title': 'Our Mission',
        'about.mission.collaboration.title': 'Collaboration',
        'about.mission.collaboration.text': 'We work with makers across Georgia to build a strong and creative community that supports innovation.',
        'about.mission.local.title': 'Local Production',
        'about.mission.local.text': 'We offer high-quality, locally manufactured products that support our economy and reduce environmental impact.',
        'about.mission.easy.title': 'Easy Production',
        'about.mission.easy.text': 'We make production simpler and more accessible for everyone - from designers to small businesses, making it easy to bring ideas to life.',
        'about.values.title': 'Our Values',
        'about.values.eco.title': 'Eco-Friendly Materials',
        'about.values.eco.text': 'We use biodegradable materials and support sustainable production practices to protect our planet for future generations.',
        'about.values.innovation.title': 'Innovation',
        'about.values.innovation.text': 'We constantly strive to improve our technologies and processes to offer the best solutions and stay at the forefront of 3D printing.',
        'about.values.quality.title': 'Quality',
        'about.values.quality.text': 'Every product is manufactured to the highest standards to ensure our customers receive the best quality and durability.',
        'about.values.community.title': 'Community',
        'about.values.community.text': 'We build a community where makers can share ideas, learn from each other, and create something extraordinary together.',
        'about.impact.title': 'How We Improve Lives',
        'about.impact.daily.title': 'Enhancing Daily Life',
        'about.impact.daily.text': 'Our products - from home organizers to decorations - help people live more organized and efficient lives. Every product is designed to solve real problems and improve daily routines.',
        'about.impact.customization.title': 'Personalization',
        'about.impact.customization.text': '3D printing allows us to create fully personalized products that match each person\'s unique needs and preferences, making everyday items truly yours.',
        'about.impact.accessibility.title': 'Accessibility',
        'about.impact.accessibility.text': 'We make 3D printing accessible to everyone - from small businesses to individual users. Our platform simplifies the entire process from concept to completion.',
        'about.impact.sustainability.title': 'Sustainability',
        'about.impact.sustainability.text': 'By using biodegradable materials and supporting local production, we create a more sustainable and environmentally friendly future for our community.',
        'about.cta.title': 'Let\'s Create Something Extraordinary Together',
        'about.cta.text': 'Whether you\'re a maker, designer, or simply have an idea you want to bring to life - we\'re here to help you every step of the way.',
        'newYear.title': '🎄 New Year Collection',
        'newYear.subtitle': 'Discover our festive Christmas products',
        'newYear.empty': 'No products available at the moment.',
        'newYear.seeAll': 'See All',
        'product.price': 'Price',
        'drawer.welcome': 'Welcome back',
        'drawer.signIn': 'Sign in',
        'drawer.createAccount': 'Create account',
        'materials.hero.title': 'FDM Printer Materials',
        'materials.hero.subtitle': 'Discover our full range of high-quality 3D printing materials',
        'materials.intro.title': 'FDM Printing Materials',
        'materials.intro.text': 'Fused Deposition Modeling (FDM) is the most popular 3D printing technology. We offer a diverse range of materials suited for various applications - from simple prototypes to high-demand industrial components.',
        'materials.specs.temp': 'Nozzle Temp',
        'materials.specs.bed': 'Bed Temp',
        'materials.specs.difficulty': 'Difficulty',
        'materials.specs.easy': 'Easy',
        'materials.specs.medium': 'Medium',
        'materials.specs.hard': 'Hard',
        'materials.specs.advanced': 'Advanced',
        'materials.comparison.title': 'Material Comparison',
        'materials.comparison.material': 'Material',
        'materials.comparison.strength': 'Strength',
        'materials.comparison.flexibility': 'Flexibility',
        'materials.comparison.temp': 'Temp Resistance',
        'materials.comparison.best': 'Best For',
        'materials.comparison.pla': 'Decorations, Prototypes',
        'materials.comparison.abs': 'Functional Parts, Mechanical Components',
        'materials.comparison.petg': 'Transparent Parts, Chemical Resistance',
        'materials.comparison.tpu': 'Flexible Parts, Toys',
        'materials.comparison.nylon': 'Industrial Components, High Load',
        'materials.tips.title': 'Helpful Tips',
        'materials.tips.temp.title': 'Temperature Control',
        'materials.tips.temp.text': 'Each material has its optimal printing temperature. Correct temperature ensures the best results and prevents printing problems.',
        'materials.tips.moisture.title': 'Moisture Control',
        'materials.tips.moisture.text': 'Filaments should be stored in a dry and ventilated place. Wet filament can cause printing problems and quality degradation.',
        'materials.tips.layer.title': 'Layer Height',
        'materials.tips.layer.text': 'Layer height affects print quality and speed. 0.1-0.2mm layers provide a smooth surface, while 0.3mm and above are faster.',
        'materials.tips.speed.title': 'Print Speed',
        'materials.tips.speed.text': 'Different materials have varying optimal print speeds. Generally, 40-60mm/s speed provides the best results for most materials.',
        'materials.overview.title': 'What is FDM Printing?',
        'materials.overview.paragraph1': 'Fused Deposition Modeling (FDM) is the most popular 3D printing technology, using thermoplastic filaments to create objects. This method is ideal for both prototyping and functional part production.',
        'materials.overview.paragraph2': 'We offer a diverse range of materials suited for various applications - from simple prototypes to high-demand industrial components.',
        'materials.types.title': 'Material Types',
        'materials.types.pla.title': 'PLA (Polylactic Acid)',
        'materials.types.pla.description': 'PLA is the most popular material for beginners. It prints easily, has a natural origin, and is biodegradable. Perfect for decorative items and prototypes.',
        'materials.types.abs.title': 'ABS (Acrylonitrile Butadiene Styrene)',
        'materials.types.abs.description': 'ABS is a strong and durable material known for its high temperature resistance. Excellent for functional parts and mechanical components.',
        'materials.types.petg.title': 'PETG (Polyethylene Terephthalate Glycol)',
        'materials.types.petg.description': 'PETG combines the ease of PLA with the strength of ABS. Transparent, chemically resistant, and perfect for functional applications.',
        'materials.types.tpu.title': 'TPU (Thermoplastic Polyurethane)',
        'materials.types.tpu.description': 'TPU is a flexible and elastic material perfect for parts that require deformation. Ideal for toys, bags, and protective covers.',
        'materials.types.nylon.title': 'Nylon',
        'materials.types.nylon.description': 'Nylon is a high-strength material known for its resistance to high temperatures and wear. Excellent for industrial and engineering applications.',
        'materials.types.specialty.title': 'Specialty Materials',
        'materials.types.specialty.description': 'We also offer specialty materials such as wood-filled, metal-filled, carbon fiber, and other composite filaments for unique properties.',
        'materials.properties.title': 'Material Properties',
        'materials.properties.easy': 'Easy',
        'materials.properties.eco': 'Eco-Friendly',
        'materials.properties.versatile': 'Versatile',
        'materials.properties.strong': 'Strong',
        'materials.properties.durable': 'Durable',
        'materials.properties.heat': 'Heat Resistant',
        'materials.properties.clear': 'Clear',
        'materials.properties.chemical': 'Chemical Resistant',
        'materials.properties.flexible': 'Flexible',
        'materials.properties.wear': 'Wear Resistant',
        'materials.properties.impact': 'Impact Resistant',
        'materials.properties.lightweight': 'Lightweight',
        'materials.properties.industrial': 'Industrial',
        'materials.properties.wood': 'Wood Effect',
        'materials.properties.metal': 'Metal Effect',
        'materials.properties.carbon': 'Carbon Fiber',
        'materials.properties.strength.title': 'Strength and Durability',
        'materials.properties.strength.text': 'Each material has its unique strength and durability characteristics. PLA is excellent for decorative items, while ABS and Nylon are ideal for functional components requiring high mechanical loads.',
        'materials.properties.temperature.title': 'Temperature Resistance',
        'materials.properties.temperature.text': 'Different materials have varying temperature characteristics. ABS and PETG handle high temperatures excellently, making them ideal for automotive and electronics components.',
        'materials.properties.flexibility.title': 'Flexibility and Elasticity',
        'materials.properties.flexibility.text': 'TPU and other flexible materials allow us to create parts that require deformation and return to their original shape. Perfect for toys, bags, and protective covers.',
        'materials.properties.finish.title': 'Surface Finish',
        'materials.properties.finish.text': 'Each material has its unique surface texture. PLA provides a smooth and glossy surface, while PETG is excellent for transparent parts. Specialty materials like wood or metal filaments provide unique visual effects.',
        'materials.applications.title': 'Applications',
        'materials.applications.home.title': 'Household Items',
        'materials.applications.home.text': 'Create personalized household items - from organizers to decorative elements. PLA and PETG are excellent for these purposes.',
        'materials.applications.prototyping.title': 'Rapid Prototyping',
        'materials.applications.prototyping.text': 'FDM printing is ideal for creating rapid prototypes. PLA\'s low cost and ease of use make it a popular choice for designers and engineers.',
        'materials.applications.art.title': 'Art and Design',
        'materials.applications.art.text': '3D printing has opened new possibilities in art. Create unique sculptures, decorations, and art pieces using specialty materials.',
        'materials.applications.functional.title': 'Functional Parts',
        'materials.applications.functional.text': 'ABS, PETG, and Nylon are excellent for producing functional parts that require high strength, durability, and temperature resistance.',
        'materials.bestPractices.title': 'Best Practices',
        'materials.bestPractices.temperature.title': 'Temperature Control',
        'materials.bestPractices.temperature.text': 'Each material has its optimal printing temperature. PLA is recommended at 190-220°C, ABS at 220-250°C, and PETG at 220-250°C. Correct temperature ensures the best results.',
        'materials.bestPractices.layer.title': 'Layer Height',
        'materials.bestPractices.layer.text': 'Layer height affects print quality and speed. 0.1-0.2mm layers provide a smooth surface, while 0.3mm and above are faster but less smooth.',
        'materials.bestPractices.storage.title': 'Material Storage',
        'materials.bestPractices.storage.text': 'Filaments should be stored in a dry and ventilated place to prevent moisture absorption. Wet filament can cause printing problems and quality degradation.',
        'materials.bestPractices.quality.title': 'Quality Control',
        'materials.bestPractices.quality.text': 'We use only high-quality filaments that undergo strict quality control. This ensures consistent and reliable printing results in every project.',
        'materials.cta.title': 'Ready to Start Your Project?',
        'materials.cta.text': 'Contact us to discuss your material needs and find the perfect solution for your project.',
        'contact.hero.title': 'Get in Touch',
        'contact.hero.subtitle': 'We\'re always here to help with your questions and projects',
        'contact.form.title': 'Send us a Message',
        'contact.form.description': 'Fill out the form below and we\'ll get back to you soon',
        'contact.form.name': 'Name',
        'contact.form.namePlaceholder': 'Enter your name',
        'contact.form.email': 'Email',
        'contact.form.emailPlaceholder': 'your.email@example.com',
        'contact.form.subject': 'Subject',
        'contact.form.subjectPlaceholder': 'What would you like to contact us about?',
        'contact.form.message': 'Message',
        'contact.form.messagePlaceholder': 'Write your message here...',
        'contact.form.submit': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.success': 'Message sent successfully! We\'ll get back to you soon.',
        'contact.error': 'An error occurred. Please try again later.',
        'contact.info.email.title': 'Email',
        'contact.info.email.text': 'info@makershub.ge',
        'contact.info.location.title': 'Location',
        'contact.info.location.text': 'Georgia',
        'contact.info.hours.title': 'Business Hours',
        'contact.info.hours.text': 'Monday - Friday: 10:00 AM - 6:00 PM',
        'product.madeBy': 'Made By',
        'product.ships': 'Ships as soon as 7 days',
        'product.color': 'Color:',
        'product.quantity': 'Quantity:',
        'product.addToCart': 'Add to Cart',
        'product.question': 'Have a question about this Product?',
        'product.loginRequired': 'You must be logged in and verified to contact the designer.',
        'product.about': 'About This Product',
        'product.noDescription': 'No description available for this product.',
        'product.information': 'Product Information',
        'product.category': 'Category',
        'product.subcategory': 'Subcategory',
        'product.createdBy': 'Created By',
        'product.shipping': 'Shipping',
        'product.shippingTime': '7-14 business days',
        'checkout.confirmOrder': 'Confirm your order',
        'checkout.confirmDescription': 'Please review your shipping details and complete the manual bank transfer to finalize.',
        'checkout.shippingDetails': 'Shipping details',
        'checkout.fullName': 'Full name*',
        'checkout.fullNamePlaceholder': 'Enter your full name',
        'checkout.company': 'Company',
        'checkout.companyPlaceholder': 'Company (optional)',
        'checkout.addressLine': 'Address line*',
        'checkout.addressLinePlaceholder': 'Street and number',
        'checkout.addressLine2': 'Address line 2',
        'checkout.addressLine2Placeholder': 'Apt, suite, etc. (optional)',
        'checkout.city': 'City*',
        'checkout.cityPlaceholder': 'City',
        'checkout.phone': 'Phone*',
        'checkout.phonePlaceholder': '+995 ...',
        'checkout.orderNotes': 'Order notes',
        'checkout.orderNotesPlaceholder': 'Add special instructions (optional)',
        'checkout.orderSummary': 'Order summary',
        'checkout.qty': 'Qty',
        'checkout.subtotal': 'Subtotal',
        'checkout.shipping': 'Shipping',
        'checkout.total': 'Total',
        'checkout.cancel': 'Cancel',
        'checkout.placingOrder': 'Placing order…',
        'checkout.placeOrder': 'Place order & show bank details',
        'checkout.orderCreated': 'Order created',
        'checkout.orderCreatedDescription': 'Include the payment reference below when you complete the bank transfer. Payments usually register within 30 minutes—once we confirm the funds we\'ll update the order status and get production underway.',
        'checkout.paymentReference': 'Payment reference',
        'checkout.copy': 'Copy',
        'checkout.transferDetails': 'Transfer details',
        'checkout.transferInstructions': 'Make a bank transfer for the total amount using the reference code above. If you\'ve already paid, the status will update automatically as soon as the transfer clears; feel free to reply to the confirmation email if you need a hand.',
        'checkout.payee': 'Payee',
        'checkout.bank': 'Bank',
        'checkout.bankAddress': 'Bank address',
        'checkout.accountNumber': 'Account number',
        'checkout.swift': 'SWIFT',
        'checkout.amount': 'Amount',
        'checkout.close': 'Close',
        'checkout.viewOrderHistory': 'View order history',
        'checkout.cartEmpty': 'Your cart is empty.',
        'checkout.fillRequired': 'Please fill in your full name, address and phone number.',
        'checkout.orderError': 'Unable to create order. Please try again.',
        'checkout.profileError': 'Unable to load saved profile details.',
        'profile.loading': 'Loading your profile…',
        'profile.title': 'Your profile',
        'profile.description': 'Manage how Factory L personalizes your experience.',
        'profile.name': 'Name',
        'profile.email': 'Email',
        'profile.accountCreated': 'Account created',
        'profile.authProvider': 'Auth provider',
        'profile.accessLevel': 'Access level',
        'profile.administrator': 'Administrator',
        'profile.customer': 'Customer',
        'profile.startProject': 'Start a new project',
        'profile.signOut': 'Sign out',
        'profile.loadError': 'Unable to load profile data.',
        'profile.recentActivity': 'Recent activity',
        'profile.noPurchases': 'You have no purchases yet',
        'profile.noPurchasesDesc': 'When you check out, your orders will appear here so you can revisit files, download invoices, or reorder in a single click.',
        'profile.latestPurchases': 'Your latest purchases',
        'profile.latestPurchasesDesc': 'Track fulfillment progress, download deliverables, and explore recommended add-ons.',
        'profile.order': 'Order',
        'profile.placedOn': 'Placed on',
        'profile.qty': 'Qty',
        'profile.viewDetails': 'View details',
        'profile.status.awaitingPayment': 'Awaiting payment',
        'profile.status.paymentReceived': 'Payment received',
        'profile.status.processing': 'Processing',
        'profile.status.fulfilled': 'Fulfilled',
        'profile.status.cancelled': 'Cancelled',
        'profile.orderDetails.awaitingTransfer': 'Awaiting your bank transfer',
        'profile.orderDetails.paymentIntro': 'We\'re holding this order until the payment arrives. Please transfer the total using the reference below so we can move your project into production. Bank transfers usually show up within 30 minutes; if you\'ve already paid, the status will update automatically once we confirm the funds.',
        'profile.orderDetails.paymentReference': 'Payment reference',
        'profile.orderDetails.copy': 'Copy',
        'profile.orderDetails.payee': 'Payee',
        'profile.orderDetails.bank': 'Bank',
        'profile.orderDetails.bankAddress': 'Bank address',
        'profile.orderDetails.accountNumber': 'Account number',
        'profile.orderDetails.swift': 'SWIFT',
        'profile.orderDetails.amount': 'Amount',
        'profile.orderDetails.paymentHelp': 'If it\'s been more than 30 minutes since you transferred the funds, reply to the confirmation email and we\'ll prioritize the review.',
        'profile.orderDetails.items': 'Items',
        'profile.orderDetails.shipping': 'Shipping',
        'profile.orderDetails.recipient': 'Recipient',
        'profile.orderDetails.company': 'Company',
        'profile.orderDetails.addressLine1': 'Address line 1',
        'profile.orderDetails.addressLine2': 'Address line 2',
        'profile.orderDetails.city': 'City',
        'profile.orderDetails.phone': 'Phone',
        'profile.orderDetails.billing': 'Billing',
        'profile.orderDetails.customerNotes': 'Customer notes',
        'profile.orderDetails.subtotal': 'Subtotal',
        'profile.orderDetails.shipping': 'Shipping',
        'profile.orderDetails.total': 'Total',
        'profile.orderDetails.close': 'Close order details',
        'cart.recentlyAdded': 'Recently Added:',
        'cart.empty': 'Your cart is empty',
        'cart.emptyDesc': 'Looks like you haven\'t added any items to your cart yet.',
        'cart.continueShopping': '← Continue Shopping',
        'cart.myCart': 'My Cart',
        'cart.item': 'item',
        'cart.items': 'items',
        'cart.orderSummary': 'Order Summary',
        'cart.subtotal': 'Subtotal',
        'cart.estimatedShipping': 'Estimated Shipping',
        'cart.free': 'Free',
        'cart.total': 'Total',
        'cart.proceedToCheckout': 'Proceed to Checkout',
        'cart.shippingNote': 'Free shipping on orders over ₾50',
    }
}